apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2020-01-30T14:10:36Z","generation":2,"labels":{"app":"dask","chart":"dask-4.1.2","component":"worker","heritage":"Helm","release":"dask"},"name":"dask-worker","namespace":"default","resourceVersion":"835169","selfLink":"/apis/apps/v1/namespaces/default/deployments/dask-worker","uid":"27f8f28a-6cbf-4ad5-89bc-b0a2e9d22e39"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"dask","component":"worker","release":"dask"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"dask","component":"worker","release":"dask"}},"spec":{"containers":[{"args":["dask-worker","tls://dask-scheduler:8786","--no-dashboard","--tls-ca-file=/etc/pki/dask-ca.pem","--tls-cert=/etc/pki/dask-cert.pem","--tls-key=/etc/pki/dask-key.pem"],"env":[{"name":"EXTRA_PIP_PACKAGES","value":"git+https://github.com/blue-yonder/tsfresh.git"}],"image":"daskdev/dask:2.9.2","imagePullPolicy":"IfNotPresent","name":"dask-worker","ports":[{"containerPort":8789,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/pki/","name":"dask-cert","readOnly":true}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"dask-cert","secret":{"defaultMode":420,"secretName":"dask-cert"}}]}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2020-01-30T14:10:36Z","lastUpdateTime":"2020-01-30T15:22:39Z","message":"ReplicaSet \"dask-worker-64c74c975\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2020-01-31T11:05:27Z","lastUpdateTime":"2020-01-31T11:05:27Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":2,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2020-01-30T14:10:36Z"
  generation: 4
  labels:
    app: dask
    chart: dask-4.1.2
    component: worker
    heritage: Helm
    release: dask
  name: dask-worker
  namespace: default
  resourceVersion: "4557039"
  selfLink: /apis/apps/v1/namespaces/default/deployments/dask-worker
  uid: 27f8f28a-6cbf-4ad5-89bc-b0a2e9d22e39
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dask
      component: worker
      release: dask
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dask
        component: worker
        release: dask
    spec:
      containers:
      - args:
        - dask-worker
        - tls://dask-scheduler:8786
        - --no-dashboard
        - --nprocs 1
        - --nthreads 1
        - --tls-ca-file=/etc/pki/dask-ca.pem
        - --tls-cert=/etc/pki/dask-cert.pem
        - --tls-key=/etc/pki/dask-key.pem
        env:
        - name: EXTRA_PIP_PACKAGES
          value: git+https://github.com/blue-yonder/tsfresh.git
        image: daskdev/dask:2.9.2
        imagePullPolicy: IfNotPresent
        name: dask-worker
        ports:
        - containerPort: 8789
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pki/
          name: dask-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dask-cert
        secret:
          defaultMode: 420
          secretName: dask-cert
status:
  conditions:
  - lastTransitionTime: "2020-01-30T14:10:36Z"
    lastUpdateTime: "2020-02-12T17:35:38Z"
    message: ReplicaSet "dask-worker-d6f97644c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-02-17T10:31:51Z"
    lastUpdateTime: "2020-02-17T10:31:51Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 4
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3
